# Generated by Django 4.2.2 on 2023-06-22 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_bookborrowcard"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookcopy",
            options={
                "permissions": (
                    ("can_see_all_borrowed", "can see all borrowed book copies"),
                    ("can_see_my_borrowed", "can see my borrowed book copies"),
                )
            },
        ),
    ]
