# Generated by Django 4.2.2 on 2023-06-22 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0003_alter_bookcopy_options"),
    ]

    operations = [
        migrations.RemoveField(model_name="bookcopy", name="available",),
        migrations.AddField(
            model_name="bookcopy",
            name="availability",
            field=models.CharField(
                choices=[("a", "Available"), ("r", "Reserved"), ("b", "Borrowed")],
                default="a",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="bookcopy",
            name="borrower",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bookcopy",
            name="due_date",
            field=models.DateField(default=None, null=True),
        ),
        migrations.DeleteModel(name="BookBorrowCard",),
    ]
