# Generated by Django 4.2.2 on 2023-06-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_bookcopy_requests"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookcopy",
            options={
                "permissions": (
                    ("can see all borrowed book copies", "can_see_all_borrowed"),
                    ("can see my borrowed book copies", "can_see_my_borrowed"),
                )
            },
        ),
    ]
